### ISSUE TITLE
Require exception

### ISSUE THREAD

**Issue by den1k** [plandes/clj-nlp-parse#1] opened 2018-03-22 19:20 UTC
The pos model is loaded. Any idea what's going on here?

```clojure
(my-ns
  (:require [zensols.nlparse.parse :refer [parse]]))

=> CompilerException java.lang.Exception: namespace 'zensols.actioncli.resource' not found, compiling:(/Users/den/Dropbox/dev/code/....) 
```

**Comment by plandes** [comment] 2018-03-22 19:22
The error is a Clojure level exception complaining it can't find a dependency namespace (basically a .clj) file.  Can you include the entire stack trace?  This is usually due to some nested exception with the real catalyst in the chain.

**Comment by den1k** [comment] 2018-03-22 19:31
Thanks for the quick response! It looks like this is a Clojure 1.9 + spec error. It complains about a misshaped `defn` at doesn't compile the namespace. I downgraded to 1.8 and the issue disappeared

**Comment by plandes** [comment] 2018-03-22 19:32
Yes, this hasn't moved to 1.9 yet.  If you want to make a pull request I'll review and merge.

**Comment by plandes** [comment] 2018-03-23 03:34
Hmm, seems like I wrote earlier asking for a pull request for the doc change but that evaporated.  Is there any way you'd be willing to submit a pull request for a doc change?  I've not looked at the model loading portion of this in a while and you'd save me a lot of time.  Thanks @den1k!

**Comment by tirkarthi** [comment] 2018-03-23 07:52
I tried running it under Clojure 1.9 . Stacktrace as below : 

```
nREPL server started on port 35217 on host 127.0.0.1 - nrepl://127.0.0.1:35217
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.9.0
OpenJDK 64-Bit Server VM 9-internal+0-2016-04-14-195246.buildd.src
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require '[zensols.nlparse.parse :refer [parse]])

CompilerException clojure.lang.ExceptionInfo: Call to clojure.core/defn did not conform to spec:
In: [2 0 3 :or :create 0] val: :create fails spec: :clojure.core.specs.alpha/or at: [:args :bs :arity-n :bodies :args :varargs :form :map :or 0] predicate: simple-symbol?
In: [2 0 3] val: {:keys [create], :or {:create nil}} fails spec: :clojure.core.specs.alpha/local-name at: [:args :bs :arity-n :bodies :args :varargs :form :sym] predicate: simple-symbol?
In: [2 0 3] val: {:keys [create], :or {:create nil}} fails spec: :clojure.core.specs.alpha/seq-binding-form at: [:args :bs :arity-n :bodies :args :varargs :form :seq] predicate: vector?
In: [2] val: ([key child-file & {:keys [create], :or {:create nil}}] (let [parent (resolve-function key false) path (resolve-resource (cond (instance? File parent) :file (function? parent) :function (instance? java.net.URL parent) :resource (string? parent) :resource true :constant) parent child-file)] (case create :file (.mkdirs path) :dir (.mkdirs (.getParentFile path)) :else) path)) fails spec: :clojure.core.specs.alpha/arg-list at: [:args :bs :arity-1 :args] predicate: vector?
 #:clojure.spec.alpha{:problems ({:path [:args :bs :arity-1 :args], :pred clojure.core/vector?, :val ([key child-file & {:keys [create], :or {:create nil}}] (let [parent (resolve-function key false) path (resolve-resource (cond (instance? File parent) :file (function? parent) :function (instance? java.net.URL parent) :resource (string? parent) :resource true :constant) parent child-file)] (case create :file (.mkdirs path) :dir (.mkdirs (.getParentFile path)) :else) path)), :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list], :in [2]} {:path [:args :bs :arity-n :bodies :args :varargs :form :sym], :pred clojure.core/simple-symbol?, :val {:keys [create], :or {:create nil}}, :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/local-name], :in [2 0 3]} {:path [:args :bs :arity-n :bodies :args :varargs :form :seq], :pred clojure.core/vector?, :val {:keys [create], :or {:create nil}}, :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/seq-binding-form], :in [2 0 3]} {:path [:args :bs :arity-n :bodies :args :varargs :form :map :or 0], :pred clojure.core/simple-symbol?, :val :create, :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/map-binding-form :clojure.core.specs.alpha/map-special-binding :clojure.core.specs.alpha/or], :in [2 0 3 :or :create 0]}), :spec #object[clojure.spec.alpha$regex_spec_impl$reify__2436 0x6eeb8611 "clojure.spec.alpha$regex_spec_impl$reify__2436@6eeb8611"], :value (resource-path "Get a path to a resource.\n  Before using this you must register resources with [[register-resource]].\n\n  ## Keys\n\n  * **:create** if `:file` then create the director(ies) on the\n  file system, otherwise if `:dir` then create all parent directories" ([key child-file & {:keys [create], :or {:create nil}}] (let [parent (resolve-function key false) path (resolve-resource (cond (instance? File parent) :file (function? parent) :function (instance? java.net.URL parent) :resource (string? parent) :resource true :constant) parent child-file)] (case create :file (.mkdirs path) :dir (.mkdirs (.getParentFile path)) :else) path)) ([key] (resolve-function key true))), :args (resource-path "Get a path to a resource.\n  Before using this you must register resources with [[register-resource]].\n\n  ## Keys\n\n  * **:create** if `:file` then create the director(ies) on the\n  file system, otherwise if `:dir` then create all parent directories" ([key child-file & {:keys [create], :or {:create nil}}] (let [parent (resolve-function key false) path (resolve-resource (cond (instance? File parent) :file (function? parent) :function (instance? java.net.URL parent) :resource (string? parent) :resource true :constant) parent child-file)] (case create :file (.mkdirs path) :dir (.mkdirs (.getParentFile path)) :else) path)) ([key] (resolve-function key true)))}, compiling:(zensols/actioncli/resource.clj:99:1)
```

As @den1k mentioned it's due to a syntax of `defn` not allowed in Clojure 1.9

**Comment by tirkarthi** [comment] 2018-03-23 07:58
It comes from here : https://github.com/plandes/clj-actioncli/blob/master/src/clojure/zensols/actioncli/resource.clj#L99 . I will open an issue there since it needs to be fixed upstream.

Sample test case to reproduce this : 

```
➜  foo lein repl
nREPL server started on port 42688 on host 127.0.0.1 - nrepl://127.0.0.1:42688
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.9.0
OpenJDK 64-Bit Server VM 9-internal+0-2016-04-14-195246.buildd.src
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (defn resource-path ([key child-file & {:keys [create] :or {:create nil}}] :foo) ([key] :bar))

CompilerException clojure.lang.ExceptionInfo: Call to clojure.core/defn did not conform to spec:
In: [1 0 3 :or :create 0] val: :create fails spec: :clojure.core.specs.alpha/or at: [:args :bs :arity-n :bodies :args :varargs :form :map :or 0] predicate: simple-symbol?
In: [1 0 3] val: {:keys [create], :or {:create nil}} fails spec: :clojure.core.specs.alpha/local-name at: [:args :bs :arity-n :bodies :args :varargs :form :sym] predicate: simple-symbol?
In: [1 0 3] val: {:keys [create], :or {:create nil}} fails spec: :clojure.core.specs.alpha/seq-binding-form at: [:args :bs :arity-n :bodies :args :varargs :form :seq] predicate: vector?
In: [1] val: ([key child-file & {:keys [create], :or {:create nil}}] :foo) fails spec: :clojure.core.specs.alpha/arg-list at: [:args :bs :arity-1 :args] predicate: vector?
 #:clojure.spec.alpha{:problems ({:path [:args :bs :arity-1 :args], :pred clojure.core/vector?, :val ([key child-file & {:keys [create], :or {:create nil}}] :foo), :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list], :in [1]} {:path [:args :bs :arity-n :bodies :args :varargs :form :sym], :pred clojure.core/simple-symbol?, :val {:keys [create], :or {:create nil}}, :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/local-name], :in [1 0 3]} {:path [:args :bs :arity-n :bodies :args :varargs :form :seq], :pred clojure.core/vector?, :val {:keys [create], :or {:create nil}}, :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/seq-binding-form], :in [1 0 3]} {:path [:args :bs :arity-n :bodies :args :varargs :form :map :or 0], :pred clojure.core/simple-symbol?, :val :create, :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/binding-form :clojure.core.specs.alpha/map-binding-form :clojure.core.specs.alpha/map-special-binding :clojure.core.specs.alpha/or], :in [1 0 3 :or :create 0]}), :spec #object[clojure.spec.alpha$regex_spec_impl$reify__2436 0x58bfc879 "clojure.spec.alpha$regex_spec_impl$reify__2436@58bfc879"], :value (resource-path ([key child-file & {:keys [create], :or {:create nil}}] :foo) ([key] :bar)), :args (resource-path ([key child-file & {:keys [create], :or {:create nil}}] :foo) ([key] :bar))}, compiling:(/tmp/form-init2778419706693753765.clj:1:1)
```

**Comment by plandes** [comment] 2018-03-23 13:29
See [clj-actioncli](https://github.com/plandes/clj-actioncli/pull/2) issue.

**Comment by tirkarthi** [comment] 2018-03-24 05:13
@den1k I hope the changes in master fixes this error. Can you please try them?

**Comment by plandes** [comment] 2018-03-31 14:56
This thread has been dormant and it currently passes all the tests under Clojure 1.9 so I am closing it.

**Closed as completed** 2018-03-31 14:55 UTC
